Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EndOfLine:
  Description: Don't enforce CRLF on Windows.
  Enabled: false
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 200
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# requires 2.3's squiggly HEREDOC support, which we can't use, yet
# see http://www.virtuouscode.com/2016/01/06/about-the-ruby-squiggly-heredoc-syntax/
Layout/HeredocIndentation:
  Enabled: false
# Need to ignore rubocop complaining about the name of the library.
Naming/FileName:
  Exclude:
    - lib/ruby-pwsh.rb
Style/RescueStandardError:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Style/ClassVars:
  Exclude:
    - lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
