---
dist: bionic
language: ruby
cache: bundler
sudo: true
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -y powershell
  - pwsh -v
script:
  - 'bundle exec rake $CHECK'
rvm:
  - 2.5.1
  - 2.7
matrix:
  include:
  - env: CHECK="rubocop"
  - env: CHECK='spec'
