name: "release"

on:
  workflow_dispatch:

jobs:
  github-release:
    name: "create release"
    runs-on: "ubuntu-latest"
    if: github.repository_owner == 'puppetlabs'

    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      - name: "get version"
        id: "get_version"
        run: |
          echo "::set-output name=version::$(jq --raw-output .version metadata.json)"

      - name: "create release"
        run: |
          gh release create "${{ steps.get_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gem:
    name: "publish gem"
    runs-on: "ubuntu-latest"
    needs: "github-release"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      - name: "setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: "build"
        run: |
          bundle exec rake build

      - name: "publish"
        run: |
          bundle exec rake push
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

  publish-module:
    name: "publish module"
    runs-on: ubuntu-20.04
    needs: publish-gem
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
          clean: true

      - name: "update readme"
        run: |
          mv pwshlib.md README.md

      - name: "build"
        uses: "docker://puppet/pdk:latest"
        with:
          args: 'build'

      - name: "publish"
        uses: "docker://puppet/pdk:latest"
        with:
          args: 'release publish --forge-token ${{ secrets.FORGE_API_KEY }} --force'
